version: '3.8'

services:
  # Название нашего сервиса (может быть любым)
  tene-frontend:
    # Указываем, что образ нужно собрать из Dockerfile в текущей директории
    build: .
    # Название, которое будет у контейнера
    container_name: tene-frontend-app
    # Перезапускать контейнер автоматически, если он упадет
    restart: unless-stopped
    ports:
      # Пробрасываем порт 80 контейнера на порт 80 нашего сервера.
      # Если порт 80 уже занят, можно использовать другой, например "8080:80"
      - "80:80"