name: Deploy Frontend to Timeweb VDS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

   
      # 4. Собираем Docker-образ и сразу загружаем его в Docker Hub
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alenasubbota/tene-frontend:latest # Убедитесь, что здесь ваш логин
          build-args: |
            VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # 5. Выполняем команды на удаленном сервере
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # [cite_start]Переходим в папку с ГЛАВНЫМ docker-compose.yml [cite: 122]
            cd ~/tene-frontend
            # [cite_start]Скачиваем последнюю версию образа приложения [cite: 124]
            docker compose pull tene-frontend
            # Перезапускаем всё. [cite_start]Docker-compose обновит только tene-frontend [cite: 126]
            docker compose up -d --no-deps --force-recreate tene-frontend